<a href="https://colab.research.google.com/github/positivezenart/100_days_python/blob/master/college_major.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd

In [2]:
df =pd.read_csv('/content/salaries_by_college_major.csv')

In [4]:
df.head()

Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
0             Accounting                 46000.0                   77100.0   
1  Aerospace Engineering                 57700.0                  101000.0   
2            Agriculture                 42600.0                   71900.0   
3           Anthropology                 36800.0                   61500.0   
4           Architecture                 41600.0                   76800.0   

   Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary  \
0                            42200.0                           152000.0   
1                            64300.0                           161000.0   
2                            36300.0                           150000.0   
3                            33800.0                           138000.0   
4                            50600.0                           136000.0   

      Group  
0  Business  
1      STEM  
2  Business  
3      HASS  
4  Business

In [12]:
print(f"Total number of rows,{df.axes[0].size}")
print(f"Total number of columns,{df.axes[1].size}")
print(f"List of columns, {list(df.columns)}")

Total number of rows,51
Total number of columns,6
List of columns, ['Undergraduate Major', 'Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary', 'Group']


In [27]:
def null_checker(df) :
  [print(f"{i}Column contains Null value") if df[i].isna().any() else print(f"{i} column has No null values") for i in df.columns ]

In [21]:
df_null_free = df.dropna()

In [22]:
df_null_free.tail()

Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
45   Political Science                 40800.0                   78200.0   
46          Psychology                 35900.0                   60400.0   
47            Religion                 34100.0                   52000.0   
48           Sociology                 36500.0                   58200.0   
49             Spanish                 34000.0                   53100.0   

    Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary Group  
45                            41200.0                           168000.0  HASS  
46                            31600.0                           127000.0  HASS  
47                            29700.0                            96400.0  HASS  
48                            30700.0                           118000.0  HASS  
49                            31000.0                            96400.0  HASS

In [28]:
null_checker(df_null_free)

Undergraduate Major column has No null values
Starting Median Salary column has No null values
Mid-Career Median Salary column has No null values
Mid-Career 10th Percentile Salary column has No null values
Mid-Career 90th Percentile Salary column has No null values
Group column has No null values


In [52]:
df_null_free['Starting Median Salary'].idxmax()
df_starting_max=df_null_free.iloc[43]
print(f"{df_starting_max[0]} college major has the hight starting Median salary as {df_starting_max[1]}")

Physician Assistant college major has the hight starting Median salary as 74300.0


Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [53]:
df_null_free['Mid-Career Median Salary'].idxmax()
df_mid_max=df_null_free.iloc[8]
print(f"{df_mid_max[0]} college major has the hight Mid Career Median salary as {df_mid_max[1]}")

Chemical Engineering college major has the hight Mid Career Median salary as 63200.0


In [55]:
df_null_free['Starting Median Salary'].idxmin()
df_starting_min=df_null_free.iloc[49]
print(f"{df_starting_min[0]} college major has the lowest starting Median salary as {df_starting_min[1]}")

Spanish college major has the lowest starting Median salary as 34000.0


In [58]:
df_mid_min=df_null_free.iloc[df_null_free['Mid-Career Median Salary'].idxmin()]
print(f"{df_mid_min[0]} college major has the lowest Mid Career Median salary as {df_mid_min[1]}")
print(f"{df_mid_min[0]} college major can expect to earn upto {df_mid_min[4]}")

Education college major has the lowest Mid Career Median salary as 34900.0
Education college major can expect to earn upto 102000.0


In [60]:
diff_salary =df_null_free['Mid-Career 90th Percentile Salary'].subtract(df_null_free['Mid-Career 10th Percentile Salary'])

In [61]:
df_null_free.insert(1,'diff_salary',diff_salary)

In [62]:
df_null_free.head()

Undergraduate Major  diff_salary  Starting Median Salary  \
0             Accounting     109800.0                 46000.0   
1  Aerospace Engineering      96700.0                 57700.0   
2            Agriculture     113700.0                 42600.0   
3           Anthropology     104200.0                 36800.0   
4           Architecture      85400.0                 41600.0   

   Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                   77100.0                            42200.0   
1                  101000.0                            64300.0   
2                   71900.0                            36300.0   
3                   61500.0                            33800.0   
4                   76800.0                            50600.0   

   Mid-Career 90th Percentile Salary     Group  
0                           152000.0  Business  
1                           161000.0      STEM  
2                           150000.0  Business  
3                           138000.0      HASS  
4                           136000.0  Business

In [65]:
low_risk = df_null_free.sort_values('diff_salary', ascending=False)

In [70]:
low_risk[['Undergraduate Major','diff_salary']].head()

Undergraduate Major  diff_salary
17           Economics     159400.0
22             Finance     147800.0
37                Math     137800.0
36           Marketing     132900.0
42          Philosophy     132500.0

In [75]:
low_risk[['Undergraduate Major','Mid-Career 90th Percentile Salary']].sort_values('Mid-Career 90th Percentile Salary',ascending=False).head()

Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [84]:
change_in_percent = (low_risk[['Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary']].pct_change(axis=1)['Mid-Career 90th Percentile Salary'] * 100).round(2)
df_null_free.insert(2,'perc_change',change_in_percent)

In [85]:
df_null_free.head()

Undergraduate Major  diff_salary  perc_change  Starting Median Salary  \
0             Accounting     109800.0       260.19                 46000.0   
1  Aerospace Engineering      96700.0       150.39                 57700.0   
2            Agriculture     113700.0       313.22                 42600.0   
3           Anthropology     104200.0       308.28                 36800.0   
4           Architecture      85400.0       168.77                 41600.0   

   Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                   77100.0                            42200.0   
1                  101000.0                            64300.0   
2                   71900.0                            36300.0   
3                   61500.0                            33800.0   
4                   76800.0                            50600.0   

   Mid-Career 90th Percentile Salary     Group  
0                           152000.0  Business  
1                           161000.0      STEM  
2                           150000.0  Business  
3                           138000.0      HASS  
4                           136000.0  Business

In [86]:
change_in_perce = df_null_free.sort_values('perc_change',ascending=False)

In [89]:
change_in_perce[['Undergraduate Major','Starting Median Salary','Mid-Career 90th Percentile Salary','perc_change']].head()

Undergraduate Major  Starting Median Salary  \
39               Music                 35900.0   
42          Philosophy                 39900.0   
5          Art History                 35800.0   
16               Drama                 35900.0   
36           Marketing                 40800.0   

    Mid-Career 90th Percentile Salary  perc_change  
39                           134000.0       401.87  
42                           168000.0       373.24  
5                            125000.0       334.03  
16                           153000.0       316.89  
36                           175000.0       315.68

In [92]:
df_null_free.groupby('Group').count()

Undergraduate Major  diff_salary  perc_change  \
Group                                                     
Business                   12           12           12   
HASS                       22           22           22   
STEM                       16           16           16   

          Starting Median Salary  Mid-Career Median Salary  \
Group                                                        
Business                      12                        12   
HASS                          22                        22   
STEM                          16                        16   

          Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary  
Group                                                                           
Business                                 12                                 12  
HASS                                     22                                 22  
STEM                                     16                                 16

In [94]:
pd.options.display.float_format = '{:,.2f}'.format
df_null_free.groupby('Group').mean()

<ipython-input-94-98e3927ceb5e>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_null_free.groupby('Group').mean()


diff_salary  perc_change  Starting Median Salary  \
Group                                                        
Business   103,958.33       240.59               44,633.33   
HASS        95,218.18       279.53               37,186.36   
STEM       101,600.00       189.75               53,862.50   

          Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
Group                                                                   
Business                 75,083.33                          43,566.67   
HASS                     62,968.18                          34,145.45   
STEM                     90,812.50                          56,025.00   

          Mid-Career 90th Percentile Salary  
Group                                        
Business                         147,525.00  
HASS                             129,363.64  
STEM                             157,625.00

OBSERVATIOn:
1. There are toally 3 bussiness groups, Bussiness, Hass, Stem. Bussiness group has 12 major, Hass has 22 major, and stem has 16 major degree
2. Starting median salary is highest for stem field majors, however percentage change in the salary over a years of carrer is substantially lower
3. Music as carrer get more salary has they get more experience.
4. Economics has low risk compared to other carrer with steady income
5. Physician Assistant college major has the hight starting Median salary as 74300.0
6. Education college major has the lowest Mid Career Median salary as 34900.0
7. Chemical Engineering college major has the hight Mid Career Median salary as 63200.0